### ISSUE TITLE
`dev` failing in CloudFoundry on push to staging

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/fs-middlelayer-api#108]
See e.g. https://circleci.com/gh/18F/fs-middlelayer-api/320

The reason for the failure is unclear. The tests all pass.

 'cf logs fs-middlelayer-api-staging --recent' doesn't provide any useful information, just notes the renaming of the instances.

I tried using `cf local` to pull the image from staging and then running it, but unrelated errors (probably similar to issues afflicting attempts to use local Docker for the project) cause that to fail.

**Comment by lauraGgit** [comment]
Closed by #109
