### ISSUE TITLE
Sprint 3 Outstanding issues

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-middlelayer-api#11]
This is not fully complete as I wasn't able to run locally without the updated admin password, but requiring some updates anyway.
- [X] I cannot accept the sprint until the jwt signature is removed from the code and converted to an `env` variable.
- [X] I would like documentation on why the rational for why our schemas are not the same as the models. As also possibly renaming the `models` directory to connote that they are models for this layer's db to help facilitate the difference more easily to an less ingratiated developer.
- [ ] For CI purposes initialize the DB into your travis script 
https://docs.travis-ci.com/user/database-setup/#PostgreSQL (Same as above)
- [X] [The Outfitters Controller](controllers/permits/applications/special-uses/commercial/temp-outfitters/index.js) has some very deeply nested code that should probably be refactored to promises. And question - is your codeClimate report being generated by your eslint rules?

**S3 Buckets**
I'm kind of wondering if there is a way to abstract this a bit further. While both your deploy and cloud.gov can leverage s3 directly, do you know if its possible to bind the app to the bucket type more at the build level, so that its not directly reliant on the aws-sdk?
- [x] Let's move the AWS config to its own file in the `config`, so that in the future it will be a bit more swappable.
- [x] Similar to above, are the s3 buckets being mocked out during tests? Let's move to that to remove external dependencies on the test suite.
- [x] The test coverage around the uploads is pretty low. Similarly, it could be helpful to move (and add) some tests for the `special-uses` utility.js into its own file.
leverage promises. See the comment in the outdated section.

**Comment by lauraGgit** [comment]
The test coverage has improved thanks to the refactor but still some files with about a C.

**Comment by lauraGgit** [comment]
These all seem to be still present except for the outfitter controller because that more or less no longer exists.

**Comment by janwilli** [comment]
Regarding your comment, "For CI purposes initialize the DB into your travis script", #148 - 'Create database from script in Travis' was completed in Sprint 5.

The following three tasks in Sprint 6 address the S3 bucket comments:
#200 - Mocking S3 buckets 
#288 - Relocate AWS initialization
#205 - Unit testing for functions

**Comment by lauraGgit** [comment]
Looks like all of these are complete 🚀
