### ISSUE TITLE
Sprint 4 Outstanding Issues

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-middlelayer-api#12]
- [x] Postgres for the test suite setup by Travis
- [x] Naming some of the anonymized request functions that are in nested promises
- [x] Clarifying the names of some of the promises
- [x] mocking out the s3 buckets for testing
- [x] Minor tweaks noted in #9 .

**Comment by janwilli** [comment]
We have the following existing or newly created tasks to address these items:

-  Postgres for the test suite setup by Travis - #148
-  Naming some of the anonymized request functions that are in nested promises - #255
-  Clarifying the names of some of the promises - #255
-  mocking out the s3 buckets for testing - #200
- Minor tweaks noted in #9 - issues #252 - 260

**Comment by lauraGgit** [comment]
LGTM! 🚀
