### ISSUE TITLE
Update purpose field char limit in db to 500 char.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-middlelayer-api#49]

**Comment by mgwalker** [comment]
Please clarify?  There's not a field in anything described in `dba/migrations/*.js` called "purpose."  The only thing I can find in the code called "purpose" is in `src/controllers/validation.json` (looks like it defines a mapping to the basic API?) and `mocks/basic.json`.

Is this functionally a duplicate of #51?

**Comment by lauraGgit** [comment]
@mgwalker I think the difference was for which permit type, but your fix for activity_description, applied to both. thanks for catching! 👍
