### ISSUE TITLE
As a special use administrator, I can accept applications that include Excel guide rosters.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-middlelayer-api#75]
The middle layer doesn’t accept Excel files for the guide roster. The form encourages guides to use an Excel template, but the middle layer API won’t accept it.

Severity: Severe - prevents application approval
Difficulty of remediation: Low - should just require adding an additional filetype to the schema

**Comment by lauraGgit** [comment]
Part of [FFP #153](https://github.com/18F/fs-permit-platform/issues/153)

**Comment by lauraGgit** [comment]
Mostly already enabled on the middlelayer. (just need to update test objects) see #111 .

For Platform need to update `guide-documentation) to `allowXls` here but need more digging: https://github.com/18F/fs-permit-platform/blob/master/frontend/src/app/application-forms/fields/file-upload.component.ts

**Comment by lauraGgit** [comment]
![image](https://user-images.githubusercontent.com/5840989/41310410-6c5e58da-6e4f-11e8-8974-8bc0c3a2fd69.png)
needs a contact

**Comment by lauraGgit** [comment]
may be on the SUDS side - because we should not be able to even create an application without an existing contact ID

**Comment by lauraGgit** [comment]
Closing in favor of FPP #223
