### ISSUE TITLE
As a special use administrator, I can search SUDS for an ePermit prefix to find all ePermit-created applications.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-middlelayer-api#76]
Severity: Moderate - confuses special use administrators
Difficulty of remediation: Low - should just be changing the schema?

**Comment by lauraGgit** [comment]
Part of [FFP #153](https://github.com/18F/fs-permit-platform/issues/153)

**Comment by lauraGgit** [comment]
Closed by #110
