### ISSUE TITLE
As a special use administrator, I can see an application’s proposed start date in the SUDS purpose field.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-middlelayer-api#77]
In SUDS applications originating from ePermit, the purpose field should include the application’s start date (for both permit types).

Severity: Moderate - confuses special use administrators
Difficulty of remediation: Low - just changing the SUDS application schema

Tasks
- [X] Update schema
- [ ] add post-translation tests

**Comment by lauraGgit** [comment]
Part of [FFP #153](https://github.com/18F/fs-permit-platform/issues/153)

**Comment by lauraGgit** [comment]
@rrefoy is this just for TempOutfitter?

**Comment by hannahkane** [comment]
Note: 
TempOutfitter: purpose field is just activity description
Non-commercial: concatenation of multiple fields (location desc, etc.)

**Comment by lauraGgit** [comment]
Update https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/validation.json#L94 to be a concat of purposefield `\n` and startDate.

**Comment by hannahkane** [comment]
Based on Wizard of Oz notes, it seems like this applies to both permit types.

**Comment by lauraGgit** [comment]
Added to schema, but not yet added tests.

**Comment by tadhg-ohiggins** [comment]
The test part appears to be covered by https://github.com/18F/fs-middlelayer-api/blob/dev/test/post-translation-test.js#L238

**Comment by lauraGgit** [comment]
verified for nc - need to check when temp gets fixed

**Comment by lauraGgit** [comment]
for temp we should add the fieldnames here: https://github.com/18F/fs-permit-platform/blob/dev/server/src/controllers/temp-outfitter.es6#L288
