### ISSUE TITLE
As a special use administrator, I can easily read the SUDS purpose field.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-middlelayer-api#78]
In SUDS applications originating from ePermit, the purpose field should include appropriate line breaks. At the moment, it includes user-created line breaks, but doesn’t break lines between fields.

<img width="653" alt="screen shot 2018-06-13 at 4 16 10 pm" src="https://user-images.githubusercontent.com/8389648/41383284-d067be04-6f24-11e8-921d-77e2bda27b43.png">
Purpose field without appropriate line breaks.

Severity: Moderate - confuses special use administrators
Difficulty of remediation: Low - probably just making sure the right “new line” characters are included in the schema for the purpose

Add in middlelayer purpose validations.js newline chars - what would work for oracle ( `\n`)

Add newline Char's here: https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/validation.json#L338

**Comment by lauraGgit** [comment]
Part of [FFP #153](https://github.com/18F/fs-permit-platform/issues/153)

**Comment by lauraGgit** [comment]
Can you say more about this?

**Comment by lauraGgit** [comment]
we can add a new line char but not necessarily be able to change this

**Comment by lauraGgit** [comment]
start with adding the `\n` to the made up field

**Comment by lauraGgit** [comment]
LG grabbing this ticket!
